export const GET_CANDIDATES_LIST = "GET_CANDIDATES_LIST";
export const GET_CANDIDATES_LIST_SUCCEED = "GET_CANDIDATES_LIST_SUCCEED";
export const GET_CANDIDATES_LIST_FAILURE = "GET_CANDIDATES_LIST_FAILURE";

export const CREATE_CANDIDATE = "CREATE_CANDIDATE";
export const CREATE_CANDIDATE_SUCCEED = "CREATE_CANDIDATE_SUCCEED";
export const CREATE_CANDIDATE_FAILURE = "CREATE_CANDIDATE_FAILURE";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_DEPARTMENTS_SUCCEED = "GET_DEPARTMENTS_SUCCEED";
export const GET_DEPARTMENTS_FAILURE = "GET_DEPARTMENTS_FAILURE";
